import { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
  container: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    backgroundColor: "#000",
  },
  header: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "12px 16px",
    borderBottom: "1px solid #1a1a1a",
    flexShrink: 0,
  },
  backButton: {
    marginRight: 12,
    padding: 4,
    background: "none",
    border: "none",
    cursor: "pointer",
  },
  configKeysButton: {
    backgroundColor: "#2563eb",
    padding: "8px 14px",
    borderRadius: 8,
    border: "none",
    color: "#fff",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    display: "flex-end",
    marginLeft: "auto",
  },
  chatSettingsButton: {
    backgroundColor: "#1a1a1a",
    padding: "8px 14px",
    borderRadius: 8,
    border: "none",
    color: "#fff",
    fontWeight: 600,
    fontSize: 14,
    cursor: "pointer",
    display: "flex-end",
    marginLeft: 8,
  },
  settingsOptionsButton: {
    backgroundColor: "#eb2525",
    padding: "8px 14px",
    borderRadius: 8,
    border: "none",
    color: "#fff",
    fontWeight: 600,
    maxWidth: 200,
    fontSize: 14,
    cursor: "pointer",
    display: "column",
  },
  backButtonText: {
    color: "#2563eb",
    fontSize: 20,
    fontWeight: 700,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 17,
    fontWeight: 600,
  },
  messageList: {
    flex: 1,
    overflowY: "auto",
    padding: 16,
    display: "flex",
    flexDirection: "column",
  },
  messageBubble: {
    maxWidth: "75%",
    borderRadius: 14,
    padding: 10,
    marginBottom: 8,
  },
  messageUserTag: {
    color: "#aaa",
    fontSize: 11,
    marginBottom: 2,
  },
  messageText: {
    color: "#fff",
    fontSize: 15,
  },
  messageTime: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 10,
    marginTop: 4,
    textAlign: "right",
  },
  inputRow: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    padding: "8px 12px 12px",
    borderTop: "1px solid #1a1a1a",
    backgroundColor: "#000",
    flexShrink: 0,
  },
  inputField: {
    flex: 1,
    marginBottom: 0,
    marginRight: 8,
  },
  sendButton: {
    backgroundColor: "#2563eb",
    paddingLeft: 16,
    paddingRight: 16,
    height: 48,
    borderRadius: 10,
    border: "none",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  sendButtonText: {
    color: "#fff",
    fontWeight: 600,
    fontSize: 15,
},
};

export const getMessageBubbleStyle = (isMe: boolean): CSSProperties => {
  return {
    ...styles.messageBubble,
    backgroundColor: isMe ? "#2563eb" : "#1a1a1a",
    alignSelf: isMe ? "flex-end" : "flex-start",
    borderBottomRightRadius: isMe ? 4 : 14,
    borderBottomLeftRadius: isMe ? 14 : 4,
  };
}